# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Integration

on: # push and pull are the events(children) that will trigger the workflow(parent)
  push:
    branches: [ "main" ]      # this means that the workflow will only run when a push is made to the main branch
  pull_request:
    branches: [ "main" ]      # this means that the workflow will only run when a pull request is made to the main branch

jobs:
  build: # this is the job that will be run when the workflow is triggered

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]      # this means that the job will be run on the latest version of node 20 and 22
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    - name: Run build
      run: npm run build

  unit-tests: # this job will run the unit tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]      # this means that the job will be run on the latest version of node 20 and 22
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Running test cases
      run: npm run test
